# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Simple-Creator
version:      1.4
version_from: lib/Email/Simple/Creator.pm
installdirs:  site
requires:
    Email::Date:                   
    Email::Simple:                 
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
